# Generated by Django 5.2 on 2025-04-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_coins_user_coins_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coins_wallet',
        ),
    ]
