# Generated by Django 5.2 on 2025-04-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_coins_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('customer', 'Customer'), ('partner', 'Partner'), ('user', 'Regular User')], max_length=20, null=True),
        ),
    ]
