# Generated by Django 5.2 on 2025-05-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
