# Generated by Django 5.2 on 2025-05-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_children_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('partner', 'Partner'), ('user', 'Regular User')], max_length=20, null=True),
        ),
    ]
