# Generated by Django 5.2 on 2025-05-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='children',
            name='years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
