# Generated by Django 5.2 on 2025-05-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_children_allergies_children_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='years',
        ),
    ]
