# Generated by Django 5.2 on 2025-06-26 17:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_children_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.child_image_upload_path),
        ),
    ]
