# Generated by Django 5.2 on 2025-07-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_children_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('customer', 'Customer'), ('partner', 'Partner'), ('user', 'Regular User')], max_length=20, null=True),
        ),
    ]
