version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_rodjendanko
    ports:
      - "8082:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=rodjendanko_backend.settings
      - PYTHONPATH=/app
      - DEBUG=1
      - DATABASE_NAME=rodjendanko_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=njeXe3f0JiosaHpYvkMtAv2M
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
  db:
    image: postgres:13
    container_name: rodjendanko_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rodjendanko_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=njeXe3f0JiosaHpYvkMtAv2M
    ports:
      - "5432:5432"

volumes:
  postgres_data:
