version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_rodjendanko
    ports:
      - "8086:8000"
    depends_on:
      - db_rodjendanko
    volumes:
      - media_volume:/app/media
    env_file:
      - stack.env
    environment:
      - DJANGO_SETTINGS_MODULE=rodjendanko_backend.settings
      - PYTHONPATH=/app
      - DEBUG=1
      - DATABASE_NAME=rodjendanko_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=njeXe3f0JiosaHpYvkMtAv2M
      - DATABASE_HOST=db_rodjendanko
      - DATABASE_PORT=5432
      - TZ=Europe/Belgrade
  db_rodjendanko:
    image: postgres:13
    container_name: rodjendanko_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rodjendanko_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=njeXe3f0JiosaHpYvkMtAv2M
      - TZ=Europe/Belgrade
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  media_volume:
