# Generated by Django 5.1.1 on 2025-04-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
