# Generated by Django 5.2 on 2025-04-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='public_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='public_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
