# Generated by Django 5.2 on 2025-04-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0003_customer_public_id_location_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='updates_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='coins',
        ),
        migrations.AlterField(
            model_name='locationimages',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playrooms.location'),
        ),
        migrations.AlterField(
            model_name='locationworkinghours',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playrooms.location'),
        ),
    ]
