# Generated by Django 5.2 on 2025-05-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0005_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
