# Generated by Django 5.2 on 2025-06-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0006_location_location_city_location_location_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationimages',
            name='location_image',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/'),
        ),
    ]
