# Generated by Django 5.2 on 2025-06-22 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0007_locationimages_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationworkinghours',
            name='event_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationimages',
            name='location_image',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
