# Generated by Django 5.2 on 2025-07-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0009_customer_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationimages',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
