# Generated by Django 5.2 on 2025-07-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0010_locationimages_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationimages',
            name='location_image_url',
        ),
    ]
