# Generated by Django 5.2 on 2025-08-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0011_remove_locationimages_location_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_featured',
            field=models.BooleanField(default=False),
        ),
    ]
