# Generated by Django 5.2 on 2025-08-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0012_location_location_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_top_priority',
            field=models.BooleanField(default=False),
        ),
    ]
