# Generated by Django 5.1.1 on 2025-09-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0013_location_location_top_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_accommodation_air_conditioning',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='location_accommodation_animator',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='location_accommodation_catering',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='location_accommodation_children_aged',
            field=models.CharField(blank=True, choices=[('0-3', '0-3 godine (bebe i mala deca)'), ('4-7', '4-7 godine (predskolci)'), ('8-12', '8-12 godine (skolski uzrast)'), ('13+', '13+ godina (tinejdžeri i odrasli)')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_accommodation_parking',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='location_accommodation_videosurveillance',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='location_accommodation_wifi',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('indoor', 'Unutrašnji prostor'), ('outdoor', 'Spoljašnji prostor'), ('mixed', 'Mešoviti prostor')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_top_priority',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
