# Generated by Django 5.1.1 on 2025-09-14 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0014_location_location_accommodation_air_conditioning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playrooms.location')),
            ],
        ),
    ]
