# Generated by Django 5.1.1 on 2025-09-14 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0015_locationcity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationcity',
            name='location',
        ),
        migrations.AlterField(
            model_name='location',
            name='location_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playrooms.locationcity'),
        ),
    ]
