# Generated by Django 5.1.1 on 2025-09-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0019_cleanup_backup_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_accommodation_children_aged',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
