# Generated by Django 5.2 on 2025-09-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playrooms', '0020_alter_location_location_accommodation_children_aged'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_max_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_min_children',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
