# Generated by Django 5.2 on 2025-04-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservices',
            name='public_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='otherservices',
            name='public_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partnerservices',
            name='public_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
