# Generated by Django 5.2 on 2025-04-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('services', '0002_customerservices_public_id_otherservices_public_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesimages',
            old_name='service_id',
            new_name='object_id',
        ),
        migrations.AddField(
            model_name='servicesimages',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
