# Generated by Django 5.2 on 2025-07-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_service_id_servicesimages_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservices',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
