# Generated by Django 5.1.1 on 2025-04-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('Na čekanju', 'Na Cekanju'), ('Prihvacen', 'Prihvacen'), ('Odbijen', 'Odbijen'), ('Otkazan', 'Otkazan')], default='Na čekanju', max_length=20),
        ),
    ]
