# Generated by Django 5.2 on 2025-04-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_bookings_booking_validation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='public_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
