# Generated by Django 5.2 on 2025-05-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_bookings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
