# Generated by Django 5.2 on 2025-05-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_bookings_booking_duration_bookings_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('NA_CEKANJU', 'Na čekanju'), ('PRIHVACEN', 'Prihvacen'), ('ODBIJEN', 'Odbijen'), ('OTKAZAN', 'Otkazan')], default='NA_CEKANJU', max_length=20),
        ),
    ]
