# Generated by Django 5.2 on 2025-05-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_bookings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
