# Generated by Django 5.2 on 2025-05-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_bookings_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='children_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
