# Generated by Django 5.2 on 2025-05-17 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_bookings_children_count'),
        ('users', '0012_children_allergies_children_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.children'),
        ),
    ]
