# Generated by Django 5.2 on 2025-06-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_bookings_child'),
        ('services', '0003_rename_service_id_servicesimages_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='customer_services',
        ),
        migrations.AddField(
            model_name='bookings',
            name='customer_services',
            field=models.ManyToManyField(to='services.customerservices'),
        ),
    ]
