# Generated by Django 5.2 on 2025-04-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_coinswallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinswallet',
            name='customer',
        ),
    ]
