# Generated by Django 5.2 on 2025-04-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_coinswallet_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinstransaction',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
