# Generated by Django 5.2 on 2025-05-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_coinstransaction_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinstransaction',
            name='public_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
